### ISSUE TITLE
Nice Base not urs tho No credits!!!!

### ISSUE THREAD

**Issue by dschaf** [Nom-Youtube/internal-fortnite#2]
![image](https://user-images.githubusercontent.com/46796744/119583383-5cc56700-bd7b-11eb-9124-f3015c4a68ba.png)

![image](https://user-images.githubusercontent.com/46796744/119583393-65b63880-bd7b-11eb-8206-ad089b702f04.png)

**Comment by vk-nom** [comment]
I left credits bud, "leaked by micca"
