### ISSUE TITLE
see mica wasnt the one who leaked it bud.

### ISSUE THREAD

**Issue by dschaf** [Nom-Youtube/internal-fortnite#3]
see mica wasnt the one who leaked it bud.

**Comment by dschaf** [comment]
xenia0 did . but he deleted his account then unreallord reupped it
https://github.com/UnrealLord/shity-fortnite-internal-source
Micca is a skid/paster

**Comment by vk-nom** [comment]
ok, feel free to stop opening issues

**Comment by dschaf** [comment]
> ok, feel free to stop opening issues

sexy ass
